// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpvminibezpmcggjpyyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwdm1pbmliZXpwbWNnZ2pweXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDUwNjAsImV4cCI6MjA2OTY4MTA2MH0.gMNHd8l5zKetRyc_aOqQuRdGoxGNo7c49qYba3e5-Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});